name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Update submodules
      run: git submodule update --init --recursive

    - name: Install GCC 13
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-13 g++-13

    - name: Set up GCC 13 as default
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100

    - name: Install Clang 19
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-19

    - name: Set up Clang 19 as default
      run: |
        sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-19 100
        sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-19 100

    - name: Build and test with GCC 13
      run: ./build.sh -c -d -t --compiler gcc

    - name: Build and test with Clang 19
      run: ./build.sh -c -d -t --compiler clang

    - name: Build release and test with GCC 13
      run: ./build.sh -c -r -t --compiler gcc

    - name: Build release and test with Clang 19
      run: ./build.sh -c -r -t --compiler clang
